200:
  pattern: '' # Default response method
201:
  pattern: '.*.201.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
202:
  pattern: '.*.202.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
400:
  pattern: '.*.400.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
401:
  pattern: '.*.401.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
402:
  pattern: '.*.402.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
403:
  pattern: '.*.403.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
404:
  pattern: '.*.404.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
422:
  pattern: '.*.422.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
500:
  pattern: '.*.500.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
502:
  pattern: '.*.502.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"
504:
  pattern: '.*.504.*' # JSON response
  template: # JSON return object
    application/json: "${env:STATUS_CODES_TEMPLATE}"